services:
  - type: web
    name: wahyudinflix2
    env: python
    plan: free
    envVars:
      - key: PYTHONPATH
        value: .
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wahyudinfl2x.app:app"
